/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sendOTP;

import com.telesign.RestClient;
import com.telesign.Util;
import com.telesign.enterprise.VerifyClient;
import java.util.HashMap;
import java.util.Scanner;


public class App {
    public static void main(String[] args) {
        String customerId = System.getenv().getOrDefault("CUSTOMER_ID", "FFFFFFFF-EEEE-DDDD-1234-AB1234567890");
        String apiKey = System.getenv().getOrDefault("API_KEY", "ABC12345yusumoN6BYsBVkh+yRJ5czgsnCehZaOYldPJdmFh6NeX8kunZ2zU1YWaUw/0wV6xfw=="); 
        String phoneNumber = System.getenv().getOrDefault("PHONE_NUMBER", "1234567890");
        String verifyCode = Util.randomWithNDigits(5);

        HashMap<String, String> params = new HashMap<>();
        params.put("verify_code", verifyCode);

        try {
            VerifyClient verifyClient = new VerifyClient(customerId, apiKey);
            RestClient.TelesignResponse telesignResponse = verifyClient.sms(phoneNumber, params);
            System.out.println("\n" + "Response HTTP status:" + telesignResponse.statusCode);
            System.out.println("Response body:" + telesignResponse.body + "\n");
            System.out.println("Please enter the verification code you were sent:");
            Scanner s = new Scanner(System.in);
            String code = s.next();
            if (verifyCode.equalsIgnoreCase(code)) {
              System.out.println("Your code is correct.");
            } else {
              System.out.println("Your code is incorrect.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
